

INSERT INTO Exercises (title, minutes, tags, focus, createdAt, updatedAt)
VALUES 
("5 Sun Salutations", 7, "Mobility, Endurance, Strength", "arms, core, legs", NOW(), NOW()),
("Standing Baby Cradle Stretch, Left/Right",  2, "Mobility", "legs", NOW(), NOW()),
("Hamstring Stretch/Reverse Lunge Left/Right", 2, "Mobility", "legs", NOW(), NOW()),
("Standing Wide-Leg Forward Fold", 1, "Mobility", "legs", NOW(), NOW()),
("Seated One Leg Forward Fold Left/Right", 2, "Mobility", "legs", NOW(), NOW()),
("Standing Quad Stretch Left/Right", 2, "Mobility", "legs", NOW(), NOW()),
("Lunge with Quad Stretch Left/Right", 2, "Mobility", "legs", NOW(), NOW()),
("Seated Butterfly Stretch", 1, "Mobility", "legs", NOW(), NOW()),
("Pigeon Pose Hip Stretch Left/Right", 2, "Mobility", "legs", NOW(), NOW()),
("Lizard Pose Hip Stretch Left/Right", 2, "Mobility", "legs", NOW(), NOW()),
("Wall Clock Shoulder Stretch Left/Right", 2, "Mobility", "arms", NOW(), NOW()),
("Eagle Arms Left/Right", 1, "Mobility", "arms", NOW(), NOW()),
("Over the Head Tricep Stretch Left/Right", 1, "Mobility", "arms", NOW(), NOW()),
("Hand Clasped Behind Back Shoulder Stretch", 1, "Mobility", "arms", NOW(), NOW()),
("Tai Qi Arm Swings", 1, "Mobility", "arms", NOW(), NOW()),
("Bridge Pose", 1, "Mobility", "core", NOW(), NOW()),
("Cat/Cow Stretch", 2, "Mobility", "core", NOW(), NOW()),
("Bow Pose", 1, "Mobility", "core", NOW(), NOW()),
("Locust Pose", 1, "Mobility", "core", NOW(), NOW()),
("25 Jumping Jacks", 3, "Endurance", "legs", NOW(), NOW()),
("3 Minute Jump Rope", 3, "Endurance", "legs", NOW(), NOW()),
("2 Minute High Knees", 2, "Endurance", "legs", NOW(), NOW()),
("1 Minute Each Direction Side Shuffle", 2, "Endurance", "legs", NOW(), NOW()),
("10 Burpees", 2, "Endurance, Strength", "arms, core, legs", NOW(), NOW()),
("15 Pushups", 1, "Strength", "arms", NOW(), NOW()),
("10 Man Makers", 2, "Strength", "arms", NOW(), NOW()),
("Side Plank Left/Right", 2, "Strength", "arms, legs, core", NOW(), NOW()),
("Down Dog", 1, "Strength", "arms, core", NOW(), NOW()),
("Down Dog Leg Lifts Left/Right", 2, "Strength", "arms, core", NOW(), NOW()),
("Down Dog Frog Jumps", 1, "Strength", "arms, core", NOW(), NOW()),
("Dolphin Push-ups", 1, "Strength", "arms", NOW(), NOW()),
("Forearm Plank", 1, "Strength", "arms, core", NOW(), NOW()),
("10 Squat Jumps", 2, "Strength", "legs", NOW(), NOW()),
("10 Mountain Climbers", 1, "Strength", "arms, legs, core", NOW(), NOW()),
("10 Walking Lunge Left/Right", 2, "Strength", "legs", NOW(), NOW()),
("15 Full Situps", 2, "Strength", "core", NOW(), NOW()),
("20 Bicycle Crunches (10 each side)", 2, "Strength", "core", NOW(), NOW()),
("20 Transverse Crunches (10 each side)", 2, "Strength", "core", NOW(), NOW()),
("Boat Pose", 1, "Strength", "core", NOW(), NOW()),
("Stretch Pose (Hollow Body)", 1, "Strength", "core", NOW(), NOW()),
("5 Core Planks Left/Right", 2, "Strength", "arms, core", NOW(), NOW()),
("10 Star Jumps", 1, "Strength", "legs", NOW(), NOW()),
("5 Minute Run 30 Seconds/Walk 45 Seconds Interval", 5, "Endurance", "legs", NOW(), NOW()),
("5 Minute Run 60 Seconds/Walk 45 Seconds Interval", 5, "Endurance", "legs", NOW(), NOW()),
("5 Minute Run 2 Minutes/Walk 30 Seconds Interval", 5, "Endurance", "legs", NOW(), NOW()),
("10 Plank Jacks", 1, "Strength", "arms, core, legs", NOW(), NOW());


select * from Exercises;